version: "3"

services:
  devcontainer:
    container_name: devcontainer
    hostname: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - base=ubuntu:20.04
        # - ubuntu_archive_url=http://mirror.kakao.com/ubuntu/
        - use_openssh_server=true
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=${USER}
      - GROUP_NAME=${USER}
    ports:
      - "2222:22"
    volumes:
      - ./data:/mnt/data
    network_mode: bridge
    restart: unless-stopped
